# coding: utf-8

# flake8: noqa
"""
    QES Quant Service API

    QES Quant Service API provides easy access to Risk/Optimization API   # noqa: E501

    OpenAPI spec version: 0.0.4
    Contact: luo.qes@wolferesearch.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into model package
from swagger_client.models.covariance_matrix_option import CovarianceMatrixOption
from swagger_client.models.factor_input import FactorInput
from swagger_client.models.factor_model import FactorModel
from swagger_client.models.job_model import JobModel
from swagger_client.models.meta_input import MetaInput
from swagger_client.models.meta_model import MetaModel
from swagger_client.models.optimization_request import OptimizationRequest
from swagger_client.models.optimization_template import OptimizationTemplate
from swagger_client.models.portfolio_model import PortfolioModel
from swagger_client.models.risk_model import RiskModel
from swagger_client.models.risk_model_option import RiskModelOption
from swagger_client.models.risk_model_request import RiskModelRequest
from swagger_client.models.risk_model_sp_risk_option import RiskModelSpRiskOption
from swagger_client.models.risk_model_template import RiskModelTemplate
from swagger_client.models.template_model import TemplateModel
from swagger_client.models.universe_model import UniverseModel
