# coding: utf-8

"""
    QES Quant Service API

    QES Quant Service API provides easy access to Risk/Optimization API   # noqa: E501

    OpenAPI spec version: 0.0.4
    Contact: luo.qes@wolferesearch.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class MetaInput(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'mnemonic': 'str'
    }

    attribute_map = {
        'name': 'name',
        'mnemonic': 'mnemonic'
    }

    def __init__(self, name=None, mnemonic=None):  # noqa: E501
        """MetaInput - a model defined in Swagger"""  # noqa: E501

        self._name = None
        self._mnemonic = None
        self.discriminator = None

        if name is not None:
            self.name = name
        if mnemonic is not None:
            self.mnemonic = mnemonic

    @property
    def name(self):
        """Gets the name of this MetaInput.  # noqa: E501

        Human readable name for the factor, should be unique across the list  # noqa: E501

        :return: The name of this MetaInput.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this MetaInput.

        Human readable name for the factor, should be unique across the list  # noqa: E501

        :param name: The name of this MetaInput.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def mnemonic(self):
        """Gets the mnemonic of this MetaInput.  # noqa: E501

        Meta Mnemonic (SEDOL, TICKER, CURRENCY, QES_GSECTOR, QES_GGROUP, QES_COUNTRY)  # noqa: E501

        :return: The mnemonic of this MetaInput.  # noqa: E501
        :rtype: str
        """
        return self._mnemonic

    @mnemonic.setter
    def mnemonic(self, mnemonic):
        """Sets the mnemonic of this MetaInput.

        Meta Mnemonic (SEDOL, TICKER, CURRENCY, QES_GSECTOR, QES_GGROUP, QES_COUNTRY)  # noqa: E501

        :param mnemonic: The mnemonic of this MetaInput.  # noqa: E501
        :type: str
        """

        self._mnemonic = mnemonic

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(MetaInput, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MetaInput):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
