# coding: utf-8

"""
    QES Quant Service API

    QES Quant Service API provides easy access to Risk/Optimization API   # noqa: E501

    OpenAPI spec version: 0.0.4
    Contact: luo.qes@wolferesearch.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class RiskModelSpRiskOption(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'shrinkage': 'float',
        'fn': 'str'
    }

    attribute_map = {
        'shrinkage': 'shrinkage',
        'fn': 'fn'
    }

    def __init__(self, shrinkage=None, fn='mean'):  # noqa: E501
        """RiskModelSpRiskOption - a model defined in Swagger"""  # noqa: E501

        self._shrinkage = None
        self._fn = None
        self.discriminator = None

        if shrinkage is not None:
            self.shrinkage = shrinkage
        if fn is not None:
            self.fn = fn

    @property
    def shrinkage(self):
        """Gets the shrinkage of this RiskModelSpRiskOption.  # noqa: E501

        Shrinkage to control the specific risk  # noqa: E501

        :return: The shrinkage of this RiskModelSpRiskOption.  # noqa: E501
        :rtype: float
        """
        return self._shrinkage

    @shrinkage.setter
    def shrinkage(self, shrinkage):
        """Sets the shrinkage of this RiskModelSpRiskOption.

        Shrinkage to control the specific risk  # noqa: E501

        :param shrinkage: The shrinkage of this RiskModelSpRiskOption.  # noqa: E501
        :type: float
        """
        if shrinkage is not None and shrinkage > 1:  # noqa: E501
            raise ValueError("Invalid value for `shrinkage`, must be a value less than or equal to `1`")  # noqa: E501
        if shrinkage is not None and shrinkage < 0:  # noqa: E501
            raise ValueError("Invalid value for `shrinkage`, must be a value greater than or equal to `0`")  # noqa: E501

        self._shrinkage = shrinkage

    @property
    def fn(self):
        """Gets the fn of this RiskModelSpRiskOption.  # noqa: E501


        :return: The fn of this RiskModelSpRiskOption.  # noqa: E501
        :rtype: str
        """
        return self._fn

    @fn.setter
    def fn(self, fn):
        """Sets the fn of this RiskModelSpRiskOption.


        :param fn: The fn of this RiskModelSpRiskOption.  # noqa: E501
        :type: str
        """
        allowed_values = ["mean", "median"]  # noqa: E501
        if fn not in allowed_values:
            raise ValueError(
                "Invalid value for `fn` ({0}), must be one of {1}"  # noqa: E501
                .format(fn, allowed_values)
            )

        self._fn = fn

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(RiskModelSpRiskOption, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RiskModelSpRiskOption):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
