# coding: utf-8

"""
    QES Quant Service API

    QES Quant Service API provides easy access to Risk/Optimization API   # noqa: E501

    OpenAPI spec version: 0.0.4
    Contact: luo.qes@wolferesearch.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class RiskModelRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'universe': 'str',
        'template': 'str',
        'start_date': 'str',
        'end_date': 'str',
        'freq': 'str'
    }

    attribute_map = {
        'universe': 'universe',
        'template': 'template',
        'start_date': 'startDate',
        'end_date': 'endDate',
        'freq': 'freq'
    }

    def __init__(self, universe=None, template=None, start_date=None, end_date=None, freq=None):  # noqa: E501
        """RiskModelRequest - a model defined in Swagger"""  # noqa: E501

        self._universe = None
        self._template = None
        self._start_date = None
        self._end_date = None
        self._freq = None
        self.discriminator = None

        if universe is not None:
            self.universe = universe
        if template is not None:
            self.template = template
        if start_date is not None:
            self.start_date = start_date
        if end_date is not None:
            self.end_date = end_date
        if freq is not None:
            self.freq = freq

    @property
    def universe(self):
        """Gets the universe of this RiskModelRequest.  # noqa: E501

        Mnemonic for Risk Estimation universe  # noqa: E501

        :return: The universe of this RiskModelRequest.  # noqa: E501
        :rtype: str
        """
        return self._universe

    @universe.setter
    def universe(self, universe):
        """Sets the universe of this RiskModelRequest.

        Mnemonic for Risk Estimation universe  # noqa: E501

        :param universe: The universe of this RiskModelRequest.  # noqa: E501
        :type: str
        """

        self._universe = universe

    @property
    def template(self):
        """Gets the template of this RiskModelRequest.  # noqa: E501

        One of the previously defined templates for risk  # noqa: E501

        :return: The template of this RiskModelRequest.  # noqa: E501
        :rtype: str
        """
        return self._template

    @template.setter
    def template(self, template):
        """Sets the template of this RiskModelRequest.

        One of the previously defined templates for risk  # noqa: E501

        :param template: The template of this RiskModelRequest.  # noqa: E501
        :type: str
        """

        self._template = template

    @property
    def start_date(self):
        """Gets the start_date of this RiskModelRequest.  # noqa: E501

        Start date (yyyy-mm-dd)  # noqa: E501

        :return: The start_date of this RiskModelRequest.  # noqa: E501
        :rtype: str
        """
        return self._start_date

    @start_date.setter
    def start_date(self, start_date):
        """Sets the start_date of this RiskModelRequest.

        Start date (yyyy-mm-dd)  # noqa: E501

        :param start_date: The start_date of this RiskModelRequest.  # noqa: E501
        :type: str
        """

        self._start_date = start_date

    @property
    def end_date(self):
        """Gets the end_date of this RiskModelRequest.  # noqa: E501

        End date (yyyy-mm-dd)  # noqa: E501

        :return: The end_date of this RiskModelRequest.  # noqa: E501
        :rtype: str
        """
        return self._end_date

    @end_date.setter
    def end_date(self, end_date):
        """Sets the end_date of this RiskModelRequest.

        End date (yyyy-mm-dd)  # noqa: E501

        :param end_date: The end_date of this RiskModelRequest.  # noqa: E501
        :type: str
        """

        self._end_date = end_date

    @property
    def freq(self):
        """Gets the freq of this RiskModelRequest.  # noqa: E501

        Frequency of risk model generation  # noqa: E501

        :return: The freq of this RiskModelRequest.  # noqa: E501
        :rtype: str
        """
        return self._freq

    @freq.setter
    def freq(self, freq):
        """Sets the freq of this RiskModelRequest.

        Frequency of risk model generation  # noqa: E501

        :param freq: The freq of this RiskModelRequest.  # noqa: E501
        :type: str
        """
        allowed_values = ["1me", "1m", "1d", "1w"]  # noqa: E501
        if freq not in allowed_values:
            raise ValueError(
                "Invalid value for `freq` ({0}), must be one of {1}"  # noqa: E501
                .format(freq, allowed_values)
            )

        self._freq = freq

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(RiskModelRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RiskModelRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
