# coding: utf-8

"""
    QES Quant Service API

    QES Quant Service API provides easy access to Risk/Optimization API   # noqa: E501

    OpenAPI spec version: 0.0.4
    Contact: luo.qes@wolferesearch.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.optimization_request import OptimizationRequest  # noqa: E501
from swagger_client.rest import ApiException


class TestOptimizationRequest(unittest.TestCase):
    """OptimizationRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOptimizationRequest(self):
        """Test OptimizationRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.optimization_request.OptimizationRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
