# coding: utf-8

"""
    QES Quant Service API

    QES Quant Service API provides easy access to Risk/Optimization API   # noqa: E501

    OpenAPI spec version: 0.0.4
    Contact: luo.qes@wolferesearch.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.job_api import JobApi  # noqa: E501
from swagger_client.rest import ApiException


class TestJobApi(unittest.TestCase):
    """JobApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.job_api.JobApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_job_list(self):
        """Test case for get_job_list

        Gets the list of applicable jobs  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
