# coding: utf-8

"""
    QES Quant Service API

    QES Quant Service API provides easy access to Risk/Optimization API   # noqa: E501

    OpenAPI spec version: 0.0.4
    Contact: luo.qes@wolferesearch.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.optimization_api import OptimizationApi  # noqa: E501
from swagger_client.rest import ApiException


class TestOptimizationApi(unittest.TestCase):
    """OptimizationApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.optimization_api.OptimizationApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_optimization(self):
        """Test case for get_optimization

        Gets optimization result for the date  # noqa: E501
        """
        pass

    def test_get_optimization_file_list(self):
        """Test case for get_optimization_file_list

        Gets optimization file list  # noqa: E501
        """
        pass

    def test_get_optimization_list(self):
        """Test case for get_optimization_list

        Gets the list of optimization tasks historical and current  # noqa: E501
        """
        pass

    def test_new_optimization_request(self):
        """Test case for new_optimization_request

        New Optimization Request  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
