# coding: utf-8

"""
    QES Quant Service API

    QES Quant Service API provides easy access to Risk/Optimization API   # noqa: E501

    OpenAPI spec version: 0.0.4
    Contact: luo.qes@wolferesearch.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.risk_model_api import RiskModelApi  # noqa: E501
from swagger_client.rest import ApiException


class TestRiskModelApi(unittest.TestCase):
    """RiskModelApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.risk_model_api.RiskModelApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_risk_model(self):
        """Test case for create_risk_model

        Creates New Risk Model  # noqa: E501
        """
        pass

    def test_get_risk_model_date_files(self):
        """Test case for get_risk_model_date_files

        Gets risk model files listing  # noqa: E501
        """
        pass

    def test_get_risk_model_date_list(self):
        """Test case for get_risk_model_date_list

        Gets risk model dates list  # noqa: E501
        """
        pass

    def test_get_risk_model_file(self):
        """Test case for get_risk_model_file

        Download a risk model file  # noqa: E501
        """
        pass

    def test_get_risk_model_list(self):
        """Test case for get_risk_model_list

        Gets the list of risk models historical and current  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
