# coding: utf-8

"""
    QES Quant Service API

    QES Quant Service API provides easy access to Risk/Optimization API   # noqa: E501

    OpenAPI spec version: 0.0.4
    Contact: luo.qes@wolferesearch.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.catalog_api import CatalogApi  # noqa: E501
from swagger_client.rest import ApiException


class TestCatalogApi(unittest.TestCase):
    """CatalogApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.catalog_api.CatalogApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_optimization_template(self):
        """Test case for create_optimization_template

        Creates new optimization template  # noqa: E501
        """
        pass

    def test_create_portfolio(self):
        """Test case for create_portfolio

        Creates / Updates Portoflio  # noqa: E501
        """
        pass

    def test_create_risk_model_template(self):
        """Test case for create_risk_model_template

        Creates / Updates Risk Model Template based on ...  # noqa: E501
        """
        pass

    def test_get_factor_list(self):
        """Test case for get_factor_list

        Gets the list of applicable factors  # noqa: E501
        """
        pass

    def test_get_meta_list(self):
        """Test case for get_meta_list

        Gets the list of applicable meta fields  # noqa: E501
        """
        pass

    def test_get_portfolio_list(self):
        """Test case for get_portfolio_list

        Gets the list of applicable portfolios  # noqa: E501
        """
        pass

    def test_get_template_list(self):
        """Test case for get_template_list

        Gets the list of appicable templates  # noqa: E501
        """
        pass

    def test_get_universe_list(self):
        """Test case for get_universe_list

        Gets the list of applicable universes  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
