# coding: utf-8

"""
    QES Quant Service API

    QES Quant Service API provides easy access to Risk/Optimization API   # noqa: E501

    OpenAPI spec version: 0.0.4
    Contact: luo.qes@wolferesearch.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.meta_model import MetaModel  # noqa: E501
from swagger_client.rest import ApiException


class TestMetaModel(unittest.TestCase):
    """MetaModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMetaModel(self):
        """Test MetaModel"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.meta_model.MetaModel()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
