/*
 * QES Quant Service API
 * QES Quant Service API provides easy access to Risk/Optimization API 
 *
 * OpenAPI spec version: 0.0.4
 * Contact: luo.qes@wolferesearch.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.RiskModel;
import io.swagger.client.model.RiskModelRequest;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for RiskModelApi
 */
@Ignore
public class RiskModelApiTest {

    private final RiskModelApi api = new RiskModelApi();

    
    /**
     * Creates New Risk Model
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createRiskModelTest() throws ApiException {
        RiskModelRequest body = null;
        String response = api.createRiskModel(body);

        // TODO: test validations
    }
    
    /**
     * Gets risk model files listing
     *
     * Returns list of files available for risk model for a date
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getRiskModelDateFilesTest() throws ApiException {
        String uuid = null;
        String date = null;
        List<String> response = api.getRiskModelDateFiles(uuid, date);

        // TODO: test validations
    }
    
    /**
     * Gets risk model dates list
     *
     * Returns dates for which risk model is available
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getRiskModelDateListTest() throws ApiException {
        String uuid = null;
        List<String> response = api.getRiskModelDateList(uuid);

        // TODO: test validations
    }
    
    /**
     * Download a risk model file
     *
     * Download risk model CSV File
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getRiskModelFileTest() throws ApiException {
        String uuid = null;
        String date = null;
        String file = null;
        api.getRiskModelFile(uuid, date, file);

        // TODO: test validations
    }
    
    /**
     * Gets the list of risk models historical and current
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getRiskModelListTest() throws ApiException {
        List<RiskModel> response = api.getRiskModelList();

        // TODO: test validations
    }
    
}
