/*
 * QES Quant Service API
 * QES Quant Service API provides easy access to Risk/Optimization API 
 *
 * OpenAPI spec version: 0.0.4
 * Contact: luo.qes@wolferesearch.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;

/**
 * CovarianceMatrixOption
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-01-22T20:31:04.892Z")
public class CovarianceMatrixOption {
  @SerializedName("interval")
  private Integer interval = null;

  @SerializedName("cov.period")
  private Integer covPeriod = null;

  @SerializedName("var.period")
  private Integer varPeriod = null;

  @SerializedName("shirinkageIntensity")
  private BigDecimal shirinkageIntensity = null;

  public CovarianceMatrixOption interval(Integer interval) {
    this.interval = interval;
    return this;
  }

   /**
   * Get interval
   * minimum: 1
   * maximum: 1000
   * @return interval
  **/
  @ApiModelProperty(value = "")
  public Integer getInterval() {
    return interval;
  }

  public void setInterval(Integer interval) {
    this.interval = interval;
  }

  public CovarianceMatrixOption covPeriod(Integer covPeriod) {
    this.covPeriod = covPeriod;
    return this;
  }

   /**
   * Get covPeriod
   * minimum: 32
   * maximum: 5000
   * @return covPeriod
  **/
  @ApiModelProperty(value = "")
  public Integer getCovPeriod() {
    return covPeriod;
  }

  public void setCovPeriod(Integer covPeriod) {
    this.covPeriod = covPeriod;
  }

  public CovarianceMatrixOption varPeriod(Integer varPeriod) {
    this.varPeriod = varPeriod;
    return this;
  }

   /**
   * Get varPeriod
   * minimum: 32
   * maximum: 5000
   * @return varPeriod
  **/
  @ApiModelProperty(value = "")
  public Integer getVarPeriod() {
    return varPeriod;
  }

  public void setVarPeriod(Integer varPeriod) {
    this.varPeriod = varPeriod;
  }

  public CovarianceMatrixOption shirinkageIntensity(BigDecimal shirinkageIntensity) {
    this.shirinkageIntensity = shirinkageIntensity;
    return this;
  }

   /**
   * Get shirinkageIntensity
   * minimum: 0
   * maximum: 1
   * @return shirinkageIntensity
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getShirinkageIntensity() {
    return shirinkageIntensity;
  }

  public void setShirinkageIntensity(BigDecimal shirinkageIntensity) {
    this.shirinkageIntensity = shirinkageIntensity;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CovarianceMatrixOption covarianceMatrixOption = (CovarianceMatrixOption) o;
    return Objects.equals(this.interval, covarianceMatrixOption.interval) &&
        Objects.equals(this.covPeriod, covarianceMatrixOption.covPeriod) &&
        Objects.equals(this.varPeriod, covarianceMatrixOption.varPeriod) &&
        Objects.equals(this.shirinkageIntensity, covarianceMatrixOption.shirinkageIntensity);
  }

  @Override
  public int hashCode() {
    return Objects.hash(interval, covPeriod, varPeriod, shirinkageIntensity);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CovarianceMatrixOption {\n");
    
    sb.append("    interval: ").append(toIndentedString(interval)).append("\n");
    sb.append("    covPeriod: ").append(toIndentedString(covPeriod)).append("\n");
    sb.append("    varPeriod: ").append(toIndentedString(varPeriod)).append("\n");
    sb.append("    shirinkageIntensity: ").append(toIndentedString(shirinkageIntensity)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

