/*
 * QES Quant Service API
 * QES Quant Service API provides easy access to Risk/Optimization API 
 *
 * OpenAPI spec version: 0.0.4
 * Contact: luo.qes@wolferesearch.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * PortfolioModel
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-01-22T20:31:04.892Z")
public class PortfolioModel {
  @SerializedName("ID")
  private String ID = null;

  @SerializedName("UPLOADEDBY")
  private String UPLOADEDBY = null;

  @SerializedName("UPLOADEDTIME")
  private String UPLOADEDTIME = null;

  public PortfolioModel ID(String ID) {
    this.ID = ID;
    return this;
  }

   /**
   * Portfolio Name
   * @return ID
  **/
  @ApiModelProperty(value = "Portfolio Name")
  public String getID() {
    return ID;
  }

  public void setID(String ID) {
    this.ID = ID;
  }

  public PortfolioModel UPLOADEDBY(String UPLOADEDBY) {
    this.UPLOADEDBY = UPLOADEDBY;
    return this;
  }

   /**
   * Associated User
   * @return UPLOADEDBY
  **/
  @ApiModelProperty(value = "Associated User")
  public String getUPLOADEDBY() {
    return UPLOADEDBY;
  }

  public void setUPLOADEDBY(String UPLOADEDBY) {
    this.UPLOADEDBY = UPLOADEDBY;
  }

  public PortfolioModel UPLOADEDTIME(String UPLOADEDTIME) {
    this.UPLOADEDTIME = UPLOADEDTIME;
    return this;
  }

   /**
   * Date on which portoflio file was uploaded
   * @return UPLOADEDTIME
  **/
  @ApiModelProperty(value = "Date on which portoflio file was uploaded")
  public String getUPLOADEDTIME() {
    return UPLOADEDTIME;
  }

  public void setUPLOADEDTIME(String UPLOADEDTIME) {
    this.UPLOADEDTIME = UPLOADEDTIME;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PortfolioModel portfolioModel = (PortfolioModel) o;
    return Objects.equals(this.ID, portfolioModel.ID) &&
        Objects.equals(this.UPLOADEDBY, portfolioModel.UPLOADEDBY) &&
        Objects.equals(this.UPLOADEDTIME, portfolioModel.UPLOADEDTIME);
  }

  @Override
  public int hashCode() {
    return Objects.hash(ID, UPLOADEDBY, UPLOADEDTIME);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PortfolioModel {\n");
    
    sb.append("    ID: ").append(toIndentedString(ID)).append("\n");
    sb.append("    UPLOADEDBY: ").append(toIndentedString(UPLOADEDBY)).append("\n");
    sb.append("    UPLOADEDTIME: ").append(toIndentedString(UPLOADEDTIME)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

