/*
 * QES Quant Service API
 * QES Quant Service API provides easy access to Risk/Optimization API 
 *
 * OpenAPI spec version: 0.0.4
 * Contact: luo.qes@wolferesearch.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.RiskModelSpRiskOption;
import java.io.IOException;

/**
 * RiskModelOption
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-01-22T20:31:04.892Z")
public class RiskModelOption {
  @SerializedName("spRisk")
  private RiskModelSpRiskOption spRisk = null;

  public RiskModelOption spRisk(RiskModelSpRiskOption spRisk) {
    this.spRisk = spRisk;
    return this;
  }

   /**
   * Get spRisk
   * @return spRisk
  **/
  @ApiModelProperty(value = "")
  public RiskModelSpRiskOption getSpRisk() {
    return spRisk;
  }

  public void setSpRisk(RiskModelSpRiskOption spRisk) {
    this.spRisk = spRisk;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RiskModelOption riskModelOption = (RiskModelOption) o;
    return Objects.equals(this.spRisk, riskModelOption.spRisk);
  }

  @Override
  public int hashCode() {
    return Objects.hash(spRisk);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RiskModelOption {\n");
    
    sb.append("    spRisk: ").append(toIndentedString(spRisk)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

