/*
 * QES Quant Service API
 * QES Quant Service API provides easy access to Risk/Optimization API 
 *
 * OpenAPI spec version: 0.0.4
 * Contact: luo.qes@wolferesearch.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * RiskModelRequest
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-01-22T20:31:04.892Z")
public class RiskModelRequest {
  @SerializedName("universe")
  private String universe = null;

  @SerializedName("template")
  private String template = null;

  @SerializedName("startDate")
  private String startDate = null;

  @SerializedName("endDate")
  private String endDate = null;

  /**
   * Frequency of risk model generation
   */
  @JsonAdapter(FreqEnum.Adapter.class)
  public enum FreqEnum {
    _1ME("1me"),
    
    _1M("1m"),
    
    _1D("1d"),
    
    _1W("1w");

    private String value;

    FreqEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static FreqEnum fromValue(String text) {
      for (FreqEnum b : FreqEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<FreqEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final FreqEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public FreqEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return FreqEnum.fromValue(String.valueOf(value));
      }
    }
  }

  @SerializedName("freq")
  private FreqEnum freq = null;

  public RiskModelRequest universe(String universe) {
    this.universe = universe;
    return this;
  }

   /**
   * Mnemonic for Risk Estimation universe
   * @return universe
  **/
  @ApiModelProperty(value = "Mnemonic for Risk Estimation universe")
  public String getUniverse() {
    return universe;
  }

  public void setUniverse(String universe) {
    this.universe = universe;
  }

  public RiskModelRequest template(String template) {
    this.template = template;
    return this;
  }

   /**
   * One of the previously defined templates for risk
   * @return template
  **/
  @ApiModelProperty(value = "One of the previously defined templates for risk")
  public String getTemplate() {
    return template;
  }

  public void setTemplate(String template) {
    this.template = template;
  }

  public RiskModelRequest startDate(String startDate) {
    this.startDate = startDate;
    return this;
  }

   /**
   * Start date (yyyy-mm-dd)
   * @return startDate
  **/
  @ApiModelProperty(value = "Start date (yyyy-mm-dd)")
  public String getStartDate() {
    return startDate;
  }

  public void setStartDate(String startDate) {
    this.startDate = startDate;
  }

  public RiskModelRequest endDate(String endDate) {
    this.endDate = endDate;
    return this;
  }

   /**
   * End date (yyyy-mm-dd)
   * @return endDate
  **/
  @ApiModelProperty(value = "End date (yyyy-mm-dd)")
  public String getEndDate() {
    return endDate;
  }

  public void setEndDate(String endDate) {
    this.endDate = endDate;
  }

  public RiskModelRequest freq(FreqEnum freq) {
    this.freq = freq;
    return this;
  }

   /**
   * Frequency of risk model generation
   * @return freq
  **/
  @ApiModelProperty(value = "Frequency of risk model generation")
  public FreqEnum getFreq() {
    return freq;
  }

  public void setFreq(FreqEnum freq) {
    this.freq = freq;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RiskModelRequest riskModelRequest = (RiskModelRequest) o;
    return Objects.equals(this.universe, riskModelRequest.universe) &&
        Objects.equals(this.template, riskModelRequest.template) &&
        Objects.equals(this.startDate, riskModelRequest.startDate) &&
        Objects.equals(this.endDate, riskModelRequest.endDate) &&
        Objects.equals(this.freq, riskModelRequest.freq);
  }

  @Override
  public int hashCode() {
    return Objects.hash(universe, template, startDate, endDate, freq);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RiskModelRequest {\n");
    
    sb.append("    universe: ").append(toIndentedString(universe)).append("\n");
    sb.append("    template: ").append(toIndentedString(template)).append("\n");
    sb.append("    startDate: ").append(toIndentedString(startDate)).append("\n");
    sb.append("    endDate: ").append(toIndentedString(endDate)).append("\n");
    sb.append("    freq: ").append(toIndentedString(freq)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

