/*
 * QES Quant Service API
 * QES Quant Service API provides easy access to Risk/Optimization API 
 *
 * OpenAPI spec version: 0.0.4
 * Contact: luo.qes@wolferesearch.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * TemplateModel
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-01-22T20:31:04.892Z")
public class TemplateModel {
  @SerializedName("TYPE")
  private String TYPE = null;

  @SerializedName("OWNER")
  private String OWNER = null;

  @SerializedName("NAME")
  private String NAME = null;

  @SerializedName("DESCRIPTION")
  private String DESCRIPTION = null;

  @SerializedName("MODIFIED_DATE")
  private String MODIFIED_DATE = null;

  @SerializedName("CONTENT")
  private String CONTENT = null;

  public TemplateModel TYPE(String TYPE) {
    this.TYPE = TYPE;
    return this;
  }

   /**
   * Applicable Process - Risk-Model, Optimization
   * @return TYPE
  **/
  @ApiModelProperty(value = "Applicable Process - Risk-Model, Optimization")
  public String getTYPE() {
    return TYPE;
  }

  public void setTYPE(String TYPE) {
    this.TYPE = TYPE;
  }

  public TemplateModel OWNER(String OWNER) {
    this.OWNER = OWNER;
    return this;
  }

   /**
   * Template Creator
   * @return OWNER
  **/
  @ApiModelProperty(value = "Template Creator")
  public String getOWNER() {
    return OWNER;
  }

  public void setOWNER(String OWNER) {
    this.OWNER = OWNER;
  }

  public TemplateModel NAME(String NAME) {
    this.NAME = NAME;
    return this;
  }

   /**
   * Unique Name
   * @return NAME
  **/
  @ApiModelProperty(value = "Unique Name")
  public String getNAME() {
    return NAME;
  }

  public void setNAME(String NAME) {
    this.NAME = NAME;
  }

  public TemplateModel DESCRIPTION(String DESCRIPTION) {
    this.DESCRIPTION = DESCRIPTION;
    return this;
  }

   /**
   * Descriptive Text
   * @return DESCRIPTION
  **/
  @ApiModelProperty(value = "Descriptive Text")
  public String getDESCRIPTION() {
    return DESCRIPTION;
  }

  public void setDESCRIPTION(String DESCRIPTION) {
    this.DESCRIPTION = DESCRIPTION;
  }

  public TemplateModel MODIFIED_DATE(String MODIFIED_DATE) {
    this.MODIFIED_DATE = MODIFIED_DATE;
    return this;
  }

   /**
   * Timestamp of last modified
   * @return MODIFIED_DATE
  **/
  @ApiModelProperty(value = "Timestamp of last modified")
  public String getMODIFIEDDATE() {
    return MODIFIED_DATE;
  }

  public void setMODIFIEDDATE(String MODIFIED_DATE) {
    this.MODIFIED_DATE = MODIFIED_DATE;
  }

  public TemplateModel CONTENT(String CONTENT) {
    this.CONTENT = CONTENT;
    return this;
  }

   /**
   * Template Content
   * @return CONTENT
  **/
  @ApiModelProperty(value = "Template Content")
  public String getCONTENT() {
    return CONTENT;
  }

  public void setCONTENT(String CONTENT) {
    this.CONTENT = CONTENT;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TemplateModel templateModel = (TemplateModel) o;
    return Objects.equals(this.TYPE, templateModel.TYPE) &&
        Objects.equals(this.OWNER, templateModel.OWNER) &&
        Objects.equals(this.NAME, templateModel.NAME) &&
        Objects.equals(this.DESCRIPTION, templateModel.DESCRIPTION) &&
        Objects.equals(this.MODIFIED_DATE, templateModel.MODIFIED_DATE) &&
        Objects.equals(this.CONTENT, templateModel.CONTENT);
  }

  @Override
  public int hashCode() {
    return Objects.hash(TYPE, OWNER, NAME, DESCRIPTION, MODIFIED_DATE, CONTENT);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TemplateModel {\n");
    
    sb.append("    TYPE: ").append(toIndentedString(TYPE)).append("\n");
    sb.append("    OWNER: ").append(toIndentedString(OWNER)).append("\n");
    sb.append("    NAME: ").append(toIndentedString(NAME)).append("\n");
    sb.append("    DESCRIPTION: ").append(toIndentedString(DESCRIPTION)).append("\n");
    sb.append("    MODIFIED_DATE: ").append(toIndentedString(MODIFIED_DATE)).append("\n");
    sb.append("    CONTENT: ").append(toIndentedString(CONTENT)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

