/*
 * QES Quant Service API
 * QES Quant Service API provides easy access to Risk/Optimization API 
 *
 * OpenAPI spec version: 0.0.4
 * Contact: luo.qes@wolferesearch.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * UniverseModel
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-01-22T20:31:04.892Z")
public class UniverseModel {
  @SerializedName("ID")
  private String ID = null;

  @SerializedName("NAME")
  private String NAME = null;

  @SerializedName("SECTOR")
  private String SECTOR = null;

  @SerializedName("COUNTRY")
  private String COUNTRY = null;

  @SerializedName("DESCRIPTION")
  private String DESCRIPTION = null;

  public UniverseModel ID(String ID) {
    this.ID = ID;
    return this;
  }

   /**
   * Unique Indentifier
   * @return ID
  **/
  @ApiModelProperty(value = "Unique Indentifier")
  public String getID() {
    return ID;
  }

  public void setID(String ID) {
    this.ID = ID;
  }

  public UniverseModel NAME(String NAME) {
    this.NAME = NAME;
    return this;
  }

   /**
   * Unique Name
   * @return NAME
  **/
  @ApiModelProperty(value = "Unique Name")
  public String getNAME() {
    return NAME;
  }

  public void setNAME(String NAME) {
    this.NAME = NAME;
  }

  public UniverseModel SECTOR(String SECTOR) {
    this.SECTOR = SECTOR;
    return this;
  }

   /**
   * Applicable Sector
   * @return SECTOR
  **/
  @ApiModelProperty(value = "Applicable Sector")
  public String getSECTOR() {
    return SECTOR;
  }

  public void setSECTOR(String SECTOR) {
    this.SECTOR = SECTOR;
  }

  public UniverseModel COUNTRY(String COUNTRY) {
    this.COUNTRY = COUNTRY;
    return this;
  }

   /**
   * Applicable Country or Geographic Region
   * @return COUNTRY
  **/
  @ApiModelProperty(value = "Applicable Country or Geographic Region")
  public String getCOUNTRY() {
    return COUNTRY;
  }

  public void setCOUNTRY(String COUNTRY) {
    this.COUNTRY = COUNTRY;
  }

  public UniverseModel DESCRIPTION(String DESCRIPTION) {
    this.DESCRIPTION = DESCRIPTION;
    return this;
  }

   /**
   * Descriptive Text
   * @return DESCRIPTION
  **/
  @ApiModelProperty(value = "Descriptive Text")
  public String getDESCRIPTION() {
    return DESCRIPTION;
  }

  public void setDESCRIPTION(String DESCRIPTION) {
    this.DESCRIPTION = DESCRIPTION;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UniverseModel universeModel = (UniverseModel) o;
    return Objects.equals(this.ID, universeModel.ID) &&
        Objects.equals(this.NAME, universeModel.NAME) &&
        Objects.equals(this.SECTOR, universeModel.SECTOR) &&
        Objects.equals(this.COUNTRY, universeModel.COUNTRY) &&
        Objects.equals(this.DESCRIPTION, universeModel.DESCRIPTION);
  }

  @Override
  public int hashCode() {
    return Objects.hash(ID, NAME, SECTOR, COUNTRY, DESCRIPTION);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UniverseModel {\n");
    
    sb.append("    ID: ").append(toIndentedString(ID)).append("\n");
    sb.append("    NAME: ").append(toIndentedString(NAME)).append("\n");
    sb.append("    SECTOR: ").append(toIndentedString(SECTOR)).append("\n");
    sb.append("    COUNTRY: ").append(toIndentedString(COUNTRY)).append("\n");
    sb.append("    DESCRIPTION: ").append(toIndentedString(DESCRIPTION)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

